<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){
        DB::table('products')->insert([
            [
                'category_id'   => 3,
                'name'          => 'Ớt ngọt Đà Lạt',
                'slug'          => 'ot-ngot-da-lat',
                'regular_price' => 35000,
                'sale_price'    => 0,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro1.webp',
                'description'   => 'Mô tả sản phẩm 1',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Hành tây',
                'slug'          => 'hanh-tay',
                'regular_price' => 25000,
                'sale_price'    => 15000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro2.webp',
                'description'   => 'Mô tả sản phẩm 2',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Snack lá ngắn',
                'slug'          => 'snack-la-ngan',
                'regular_price' => 75000,
                'sale_price'    => 60000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro3.webp',
                'description'   => 'Mô tả sản phẩm 3',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Cam canh Hà Giang',
                'slug'          => 'cam-canh-ha-giang',
                'regular_price' => 65000,
                'sale_price'    => 55000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro4.webp',
                'description'   => 'Mô tả sản phẩm 4',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 4,
                'name'          => 'Nho không hạt',
                'slug'          => 'nho-khong-hat',
                'regular_price' => 300000,
                'sale_price'    => 250000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro5.webp',
                'description'   => 'Mô tả sản phẩm 5',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          =>'Thăn Lưng Bò Mỹ Black Angus, Rib Eye (500gr)',
                'slug'          => 'than-lung-bo-my-black-angus-rib-eye-500gr',
                'regular_price'=> 900000,
                'sale_price'    => 0,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro6.webp',
                'description'   => 'Mô tả sản phẩm 6',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          => 'BẸ VAI BÒ MỸ, CHUCK FLAP (500GR)',
                'slug'          => 'be-vai-bo-my-chuck-flap-500gr',
                'regular_price' => 300000,
                'sale_price'    => 260000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro7.webp',
                'description'   => 'Mô tả sản phẩm 7',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          => 'Đầu Than Bò Mỹ (500gr)',
                'slug'          => 'dau-than-bo-my-500gr',
                'regular_price' => 250000,
                'sale_price'    => 200000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro8.webp',
                'description'   => 'Mô tả sản phẩm 8',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 2,
                'name'          => 'Bánh Tráng Cuốn Thịt Heo',
                'slug'          => 'banh-trang-cuon-thit-heo',
                'regular_price' => 25000,
                'sale_price'    => 20000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro9.webp',
                'description'   => 'Mô tả sản phẩm 9',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 2,
                'name'          => 'Gà Sốt Nước Tương',
                'slug'          => 'ga-sot-nuoc-tuong',
                'regular_price' => 150000,
                'sale_price'    => 120000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro10.webp',
                'description'   => 'Mô tả sản phẩm 10',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Ớt ngọt Đà Lạt',
                'slug'          => 'ot-ngot-da-lat',
                'regular_price' => 35000,
                'sale_price'    => 0,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro1.webp',
                'description'   => 'Mô tả sản phẩm 1',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Hành tây',
                'slug'          => 'hanh-tay',
                'regular_price' => 25000,
                'sale_price'    => 15000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro2.webp',
                'description'   => 'Mô tả sản phẩm 2',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Snack lá ngắn',
                'slug'          => 'snack-la-ngan',
                'regular_price' => 75000,
                'sale_price'    => 60000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro3.webp',
                'description'   => 'Mô tả sản phẩm 3',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Cam canh Hà Giang',
                'slug'          => 'cam-canh-ha-giang',
                'regular_price' => 65000,
                'sale_price'    => 55000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro4.webp',
                'description'   => 'Mô tả sản phẩm 4',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 4,
                'name'          => 'Nho không hạt',
                'slug'          => 'nho-khong-hat',
                'regular_price' => 300000,
                'sale_price'    => 250000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro5.webp',
                'description'   => 'Mô tả sản phẩm 5',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          =>'Thăn Lưng Bò Mỹ Black Angus, Rib Eye (500gr)',
                'slug'          => 'than-lung-bo-my-black-angus-rib-eye-500gr',
                'regular_price'=> 900000,
                'sale_price'    => 0,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro6.webp',
                'description'   => 'Mô tả sản phẩm 6',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          => 'BẸ VAI BÒ MỸ, CHUCK FLAP (500GR)',
                'slug'          => 'be-vai-bo-my-chuck-flap-500gr',
                'regular_price' => 300000,
                'sale_price'    => 260000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro7.webp',
                'description'   => 'Mô tả sản phẩm 7',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          => 'Đầu Than Bò Mỹ (500gr)',
                'slug'          => 'dau-than-bo-my-500gr',
                'regular_price' => 250000,
                'sale_price'    => 200000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro8.webp',
                'description'   => 'Mô tả sản phẩm 8',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 2,
                'name'          => 'Bánh Tráng Cuốn Thịt Heo',
                'slug'          => 'banh-trang-cuon-thit-heo',
                'regular_price' => 25000,
                'sale_price'    => 20000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro9.webp',
                'description'   => 'Mô tả sản phẩm 9',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 2,
                'name'          => 'Gà Sốt Nước Tương',
                'slug'          => 'ga-sot-nuoc-tuong',
                'regular_price' => 150000,
                'sale_price'    => 120000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro10.webp',
                'description'   => 'Mô tả sản phẩm 10',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Ớt ngọt Đà Lạt',
                'slug'          => 'ot-ngot-da-lat',
                'regular_price' => 35000,
                'sale_price'    => 0,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro1.webp',
                'description'   => 'Mô tả sản phẩm 1',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Hành tây',
                'slug'          => 'hanh-tay',
                'regular_price' => 25000,
                'sale_price'    => 15000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro2.webp',
                'description'   => 'Mô tả sản phẩm 2',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Snack lá ngắn',
                'slug'          => 'snack-la-ngan',
                'regular_price' => 75000,
                'sale_price'    => 60000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro3.webp',
                'description'   => 'Mô tả sản phẩm 3',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Cam canh Hà Giang',
                'slug'          => 'cam-canh-ha-giang',
                'regular_price' => 65000,
                'sale_price'    => 55000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro4.webp',
                'description'   => 'Mô tả sản phẩm 4',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 4,
                'name'          => 'Nho không hạt',
                'slug'          => 'nho-khong-hat',
                'regular_price' => 300000,
                'sale_price'    => 250000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro5.webp',
                'description'   => 'Mô tả sản phẩm 5',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          =>'Thăn Lưng Bò Mỹ Black Angus, Rib Eye (500gr)',
                'slug'          => 'than-lung-bo-my-black-angus-rib-eye-500gr',
                'regular_price'=> 900000,
                'sale_price'    => 0,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro6.webp',
                'description'   => 'Mô tả sản phẩm 6',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          => 'BẸ VAI BÒ MỸ, CHUCK FLAP (500GR)',
                'slug'          => 'be-vai-bo-my-chuck-flap-500gr',
                'regular_price' => 300000,
                'sale_price'    => 260000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro7.webp',
                'description'   => 'Mô tả sản phẩm 7',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          => 'Đầu Than Bò Mỹ (500gr)',
                'slug'          => 'dau-than-bo-my-500gr',
                'regular_price' => 250000,
                'sale_price'    => 200000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro8.webp',
                'description'   => 'Mô tả sản phẩm 8',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 2,
                'name'          => 'Bánh Tráng Cuốn Thịt Heo',
                'slug'          => 'banh-trang-cuon-thit-heo',
                'regular_price' => 25000,
                'sale_price'    => 20000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro9.webp',
                'description'   => 'Mô tả sản phẩm 9',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 2,
                'name'          => 'Gà Sốt Nước Tương',
                'slug'          => 'ga-sot-nuoc-tuong',
                'regular_price' => 150000,
                'sale_price'    => 120000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro10.webp',
                'description'   => 'Mô tả sản phẩm 10',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Ớt ngọt Đà Lạt',
                'slug'          => 'ot-ngot-da-lat',
                'regular_price' => 35000,
                'sale_price'    => 0,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro1.webp',
                'description'   => 'Mô tả sản phẩm 1',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Hành tây',
                'slug'          => 'hanh-tay',
                'regular_price' => 25000,
                'sale_price'    => 15000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro2.webp',
                'description'   => 'Mô tả sản phẩm 2',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Snack lá ngắn',
                'slug'          => 'snack-la-ngan',
                'regular_price' => 75000,
                'sale_price'    => 60000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro3.webp',
                'description'   => 'Mô tả sản phẩm 3',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Cam canh Hà Giang',
                'slug'          => 'cam-canh-ha-giang',
                'regular_price' => 65000,
                'sale_price'    => 55000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro4.webp',
                'description'   => 'Mô tả sản phẩm 4',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 4,
                'name'          => 'Nho không hạt',
                'slug'          => 'nho-khong-hat',
                'regular_price' => 300000,
                'sale_price'    => 250000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro5.webp',
                'description'   => 'Mô tả sản phẩm 5',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          =>'Thăn Lưng Bò Mỹ Black Angus, Rib Eye (500gr)',
                'slug'          => 'than-lung-bo-my-black-angus-rib-eye-500gr',
                'regular_price'=> 900000,
                'sale_price'    => 0,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro6.webp',
                'description'   => 'Mô tả sản phẩm 6',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          => 'BẸ VAI BÒ MỸ, CHUCK FLAP (500GR)',
                'slug'          => 'be-vai-bo-my-chuck-flap-500gr',
                'regular_price' => 300000,
                'sale_price'    => 260000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro7.webp',
                'description'   => 'Mô tả sản phẩm 7',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          => 'Đầu Than Bò Mỹ (500gr)',
                'slug'          => 'dau-than-bo-my-500gr',
                'regular_price' => 250000,
                'sale_price'    => 200000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro8.webp',
                'description'   => 'Mô tả sản phẩm 8',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 2,
                'name'          => 'Bánh Tráng Cuốn Thịt Heo',
                'slug'          => 'banh-trang-cuon-thit-heo',
                'regular_price' => 25000,
                'sale_price'    => 20000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro9.webp',
                'description'   => 'Mô tả sản phẩm 9',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 2,
                'name'          => 'Gà Sốt Nước Tương',
                'slug'          => 'ga-sot-nuoc-tuong',
                'regular_price' => 150000,
                'sale_price'    => 120000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro10.webp',
                'description'   => 'Mô tả sản phẩm 10',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Ớt ngọt Đà Lạt',
                'slug'          => 'ot-ngot-da-lat',
                'regular_price' => 35000,
                'sale_price'    => 0,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro1.webp',
                'description'   => 'Mô tả sản phẩm 1',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Hành tây',
                'slug'          => 'hanh-tay',
                'regular_price' => 25000,
                'sale_price'    => 15000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro2.webp',
                'description'   => 'Mô tả sản phẩm 2',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Snack lá ngắn',
                'slug'          => 'snack-la-ngan',
                'regular_price' => 75000,
                'sale_price'    => 60000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro3.webp',
                'description'   => 'Mô tả sản phẩm 3',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 3,
                'name'          => 'Cam canh Hà Giang',
                'slug'          => 'cam-canh-ha-giang',
                'regular_price' => 65000,
                'sale_price'    => 55000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro4.webp',
                'description'   => 'Mô tả sản phẩm 4',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 4,
                'name'          => 'Nho không hạt',
                'slug'          => 'nho-khong-hat',
                'regular_price' => 300000,
                'sale_price'    => 250000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro5.webp',
                'description'   => 'Mô tả sản phẩm 5',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          =>'Thăn Lưng Bò Mỹ Black Angus, Rib Eye (500gr)',
                'slug'          => 'than-lung-bo-my-black-angus-rib-eye-500gr',
                'regular_price'=> 900000,
                'sale_price'    => 0,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro6.webp',
                'description'   => 'Mô tả sản phẩm 6',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          => 'BẸ VAI BÒ MỸ, CHUCK FLAP (500GR)',
                'slug'          => 'be-vai-bo-my-chuck-flap-500gr',
                'regular_price' => 300000,
                'sale_price'    => 260000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro7.webp',
                'description'   => 'Mô tả sản phẩm 7',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 1,
                'name'          => 'Đầu Than Bò Mỹ (500gr)',
                'slug'          => 'dau-than-bo-my-500gr',
                'regular_price' => 250000,
                'sale_price'    => 200000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro8.webp',
                'description'   => 'Mô tả sản phẩm 8',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 2,
                'name'          => 'Bánh Tráng Cuốn Thịt Heo',
                'slug'          => 'banh-trang-cuon-thit-heo',
                'regular_price' => 25000,
                'sale_price'    => 20000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro9.webp',
                'description'   => 'Mô tả sản phẩm 9',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
            [
                'category_id'   => 2,
                'name'          => 'Gà Sốt Nước Tương',
                'slug'          => 'ga-sot-nuoc-tuong',
                'regular_price' => 150000,
                'sale_price'    => 120000,
                'stock_qty'     => mt_rand(0, 50),
                'is_active'     => mt_rand(0, 1),
                'thumbnail'     => 'pro10.webp',
                'description'   => 'Mô tả sản phẩm 10',
                'created_at'    => Carbon::now()->subDays(mt_rand(1, 30))->subHours(mt_rand(1, 24))->subMinutes(mt_rand(1, 60))->format('Y-m-d H:i:s'),
                'updated_at'    => Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);
    }
}
